{
    "2023-06-01": [
        {
            "campaign_name": "전환_아미노포켓(NEW)",
            "campaign_id": "23853721079000311",
            "account_name": "Aminotree",
            "impressions": "12",
            "clicks": "0",
            "spend": "230",
            "actions": [
                {"action_type": "onsite_web_app_view_content", "value": "3"},
                {"action_type": "view_content", "value": "3"},
                {"action_type": "onsite_web_view_content", "value": "3"},
                {"action_type": "omni_view_content", "value": "3"},
                {
                    "action_type": "offsite_conversion.fb_pixel_view_content",
                    "value": "3",
                },
            ],
            "action_values": [
                {"action_type": "omni_view_content", "value": "192400"},
                {
                    "action_type": "offsite_conversion.fb_pixel_view_content",
                    "value": "192400",
                },
                {"action_type": "onsite_web_app_view_content", "value": "192400"},
                {"action_type": "onsite_web_view_content", "value": "192400"},
                {"action_type": "view_content", "value": "192400"},
            ],
            "date_start": "2023-06-01",
            "date_stop": "2023-06-01",
            "device_platform": "desktop",
        },
        {
            "campaign_name": "전환_ 아미노포켓(NEW)",
            "campaign_id": "23853721079000311",
            "account_name": "Aminotree",
            "impressions": "2123",
            "clicks": "20",
            "spend": "67335",
            "actions": [
                {"action_type": "omni_initiated_checkout", "value": "3"},
                {"action_type": "onsite_web_app_view_content", "value": "50"},
                {"action_type": "onsite_web_purchase", "value": "1"},
                {"action_type": "post_engagement", "value": "21"},
                {"action_type": "page_engagement", "value": "21"},
                {"action_type": "purchase", "value": "1"},
                {"action_type": "onsite_web_app_purchase", "value": "1"},
                {"action_type": "view_content", "value": "50"},
                {"action_type": "landing_page_view", "value": "12"},
                {"action_type": "onsite_web_view_content", "value": "50"},
                {"action_type": "omni_view_content", "value": "50"},
                {
                    "action_type": "offsite_conversion.fb_pixel_view_content",
                    "value": "50",
                },
                {"action_type": "post_reaction", "value": "3"},
                {
                    "action_type": "offsite_conversion.fb_pixel_initiate_checkout",
                    "value": "3",
                },
                {"action_type": "offsite_conversion.fb_pixel_purchase", "value": "1"},
                {"action_type": "initiate_checkout", "value": "3"},
                {"action_type": "link_click", "value": "18"},
                {"action_type": "omni_purchase", "value": "1"},
            ],
            "action_values": [
                {"action_type": "omni_view_content", "value": "2954500"},
                {"action_type": "onsite_web_purchase", "value": "31200"},
                {
                    "action_type": "offsite_conversion.fb_pixel_initiate_checkout",
                    "value": "686400",
                },
                {"action_type": "initiate_checkout", "value": "686400"},
                {
                    "action_type": "offsite_conversion.fb_pixel_view_content",
                    "value": "2954500",
                },
                {"action_type": "omni_initiated_checkout", "value": "686400"},
                {"action_type": "onsite_web_app_view_content", "value": "2954500"},
                {"action_type": "onsite_web_view_content", "value": "2954500"},
                {"action_type": "omni_purchase", "value": "31200"},
                {"action_type": "view_content", "value": "2954500"},
                {"action_type": "onsite_web_app_purchase", "value": "31200"},
                {
                    "action_type": "offsite_conversion.fb_pixel_purchase",
                    "value": "31200",
                },
                {"action_type": "purchase", "value": "31200"},
            ],
            "date_start": "2023-06-01",
            "date_stop": "2023-06-01",
            "device_platform": "mobile_app",
        },
        {
            "campaign_name": "전환_아미노포켓(NEW)",
            "campaign_id": "23853721079000311",
            "account_name": "Aminotree",
            "impressions": "3",
            "clicks": "0",
            "spend": "36",
            "date_start": "2023-06-01",
            "date_stop": "2023-06-01",
            "device_platform": "mobile_web",
        },
    ]
}
